name: Test Pull Request
on:   
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/README.md'
      - 'templates'
      - 'utils/docker'
      - 'utils/scripts'

jobs:
  test_image_deployment: 
    name: Test Image Deployment
    uses: ./.github/workflows/test_image_deployment.yaml
    