name: Deploy to ECR Repository
run-name: >
  ${{ github.sha }} - "${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message }}"
on:
  pull_request:
    types:
      - closed
    branches:
      - Development
      - development
      - production
      - Production
      - main
      - feat/github-workflow
      - 'release*'
    paths-ignore:
      - '**/README.md'
      - 'docs'
      - '.dockerignore'
      - '.gitignore'

jobs:

  test_image_deployment: 
    name: Test Image Deployment
    uses: ./.github/workflows/test_image_deployment.yaml
  re_tag_current_latest:
    name: Re-tag Current Dev Image from latest
    uses: ./.github/workflows/re_tag_current_image.yaml
    needs: test_image_deployment
    permissions:
      id-token: write
      contents: read
    with:
      AWS_ECR_REPOSITORY: ${{ github.event.pull_request.base.ref == 'production' && vars.AWS_PROD_ECR_REPOSITORY || vars.AWS_DEV_ECR_REPOSITORY }}
      AWS_REGION: ${{ github.event.pull_request.base.ref == 'production' && vars.AWS_PROD_REGION || vars.AWS_DEV_REGION }}
      IMAGE_TAG_SUFFIX: ${{ vars.IMAGE_TAG_SUFFIX || 'latest' }}
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  push_to_ecr:
    name: Push to Dev ecr registry
    needs: re_tag_current_latest
    uses: ./.github/workflows/push_image_to_ecr.yaml
    permissions:
      id-token: write
      contents: read
    with:
      IMAGE_TAG_SUFFIX: ${{ vars.IMAGE_TAG_SUFFIX || 'latest' }}
      ENVIRONMENT: ${{ github.event.pull_request.base.ref }}
      AWS_ECR_REPOSITORY: ${{ github.event.pull_request.base.ref == 'production' && vars.AWS_PROD_ECR_REPOSITORY || vars.AWS_DEV_ECR_REPOSITORY }}
      AWS_REGION: ${{ github.event.pull_request.base.ref == 'production' && vars.AWS_PROD_REGION || vars.AWS_DEV_REGION }}
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      DOCKERFILE_PATH: ${{ vars.DOCKERFILE_PATH || '.' }}
  git_ops:
    needs: push_to_ecr
    uses: ./.github/workflows/update-gitops.yaml
    permissions:
      id-token: write
      contents: read
    with:
      APP_NAME: ${{ vars.APP_NAME }}
      AWS_ECR_REPOSITORY: ${{ github.event.pull_request.base.ref == 'production' && vars.AWS_PROD_ECR_REPOSITORY || vars.AWS_DEV_ECR_REPOSITORY }}
      AWS_REGION: ${{ github.event.pull_request.base.ref == 'production' && vars.AWS_PROD_REGION || vars.AWS_DEV_REGION }}
      GIT_OPS_REPOSITORY:  ${{ vars.GIT_OPS_REPOSITORY }}
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      IMAGE_TAG_SUFFIX: ${{ vars.IMAGE_TAG_SUFFIX || 'latest' }}
      ENVIRONMENT: ${{ github.event.pull_request.base.ref }}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
